-- What is the total revenue generated by male vs. female customers? --

select sum(purchase_amount) revenue,gender
from customer
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount? --
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Which are the top 5 products with the highest average review rating?--
select item_purchased,round(avg(review_rating::numeric),2) as avg_review
from customer 
group by item_purchased 
order by avg_review desc
limit 5;

-- Compare the average purchase amounts between Standard and Express shipping. --
select round(avg(purchase_amount),2),shipping_type
from customer 
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. --
select count(customer_id) as total_customers,
subscription_status ,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_spend
from customer 
group by subscription_status
order by total_spend,avg_spend desc

-- Which 5 products have the highest percentage of purchases with discounts applied? --
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New, Returning,
--and Loyal based on their total number of previous purchases, and show the count of each segment. --
with cte as(
select customer_id,previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer)
select customer_segment,count(*) as count_of_segments
from cte
group by customer_segment

-- What are the top 3 most purchased products within each category? --
with cte as(
	select item_purchased,category,
	count(customer_id) as total_orders,
	Row_number() over(partition by category order by count(customer_id) desc) as item_rnk
	from customer 
	group by category,item_purchased
)
	select item_rnk,category, item_purchased, total_orders
	from cte where item_rnk <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? --
select count(customer_id) as repeat_buyers,subscription_status from customer
	where previous_purchases > 5
	group by subscription_status;

-- What is the revenue contribution of each age group? --
select sum(purchase_amount) as revenue,age_group
from customer
group by age_group
order by revenue desc